### ISSUE TITLE
WOA 5 release checklist

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#15]
- [x] internal Slack channels
- [x] public Slack channels
- [x] twitter
- [x] email to partners
- [x] email to those who requested emails

**Comment by vielmetti** [comment]
done
