### ISSUE TITLE
Works on ARM 11 editorial calendar (W27, July)

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#32]
Ideas go here for WOA 11.

- [x] ARM and HPC "building momentum" report out of Frankfurt https://www.nextplatform.com/2017/06/30/momentum-building-arm-hpc/ commentary on Hacker News https://news.ycombinator.com/item?id=14673154
- [ ] Odroid C2 mainline kernel https://twitter.com/armbian/status/880761002572357634
- [ ] Armbian https://www.armbian.com/
- [ ] Xen 4.9 release notes #35 https://blog.xenproject.org/2017/06/28/whats-new-in-the-xen-project-hypervisor-4-9/ 
- [ ] Kubernetes 1.7 - how well does it work on ARM? New tutorial? #34 http://blog.kubernetes.io/2017/06/kubernetes-1.7-security-hardening-stateful-application-extensibility-updates.html?m=1  
- [ ] Kubernetes 1.7 release notes, includes ARM binaries! #34 https://groups.google.com/forum/#!topic/kubernetes-announce/NNVPGTyWAwg 
- [ ] ARM64 kernel speedups for AES-GCM crypto from Ard https://www.spinics.net/lists/linux-crypto/msg26953.html

**Comment by vielmetti** [comment]
Working in a branch! https://github.com/vielmetti/worksonarm-news/tree/2017-W27 is where you want to go if you want to follow along, or if you have PRs directly to add entries. (I don't expect you will, but just in case....)

**Comment by vielmetti** [comment]
Branch pushed to master, and we're all in for the week. The AES-GCM crypto from Ard did not go into this issue, and I wrote less about the Odroid C2 (because there was less to say).

**Comment by vielmetti** [comment]
Slow week because of July 4....
